load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "labtools_import_test",
    srcs = ["labtools_import_test.py"],
    deps = [
        "//labtools",
        "@pip//absl_py",
    ],
)
